In [ ]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])

In [6]:
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
# ^fills with numbers incremented from 0-1 of array size = 11

In [14]:
# now lets move onto multi-dimensional arrays

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [22]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
n[0,0]

np.int64(1)

In [24]:
n[0,2]


np.int64(3)

In [25]:
n[0,1] = 20

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [27]:
n[0]

array([ 1, 20,  3])

In [28]:
n[0] = [20,30,40]

In [29]:
n


array([[20, 30, 40],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [30]:
n[:,1]

array([30,  5,  8])

In [31]:
# ^ gets second column

In [32]:
# now lets get into randomly generated arrays

In [33]:
np.random.rand(5, 2)

array([[0.71553464, 0.52398267],
       [0.1009087 , 0.20449979],
       [0.16126348, 0.47753371],
       [0.18752885, 0.47196239],
       [0.08167182, 0.89542178]])

In [35]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
# .seed is like a minecraft seed, it'll be the same random numbers everytime like seed 2 would be the same on my pc and your pc

In [38]:
np.random.seed(2)
np.random.randn(5, 2)
# .rand vs .randn: 
# .rand is standard distrbution (0-1) and .randn is normal distribution (centered around 0)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [39]:
np.random.seed(2)
100 * np.random.rand(5, 2)
# if we wanna do for example 0-100, then multiply by 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [41]:
np.random.seed(2) 
np.random.randint(low = 0, high = 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [42]:
# moving onto element-wise operations

In [43]:
a = np.arange(5) 
a

array([0, 1, 2, 3, 4])

In [44]:
a + 1

array([1, 2, 3, 4, 5])

In [45]:
a * 2

array([0, 2, 4, 6, 8])

In [46]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [47]:
# basically arithematic operations on each element in the list

In [48]:
b = np.arange(5)

In [49]:
a + b

array([0, 2, 4, 6, 8])

In [50]:
a

array([0, 1, 2, 3, 4])

In [51]:
b

array([0, 1, 2, 3, 4])

In [52]:
a + b

array([0, 2, 4, 6, 8])

In [53]:
# comparison operations now

In [54]:
a >= 2 

array([False, False,  True,  True,  True])

In [55]:
b

array([0, 1, 2, 3, 4])

In [57]:
a == b

array([ True,  True,  True,  True,  True])

In [58]:
a > b 

array([False, False, False, False, False])

In [60]:
a[a>b]
# returns the elements in "a" for which the condition "a>b" is true
# since a == b, none are true 

array([], dtype=int64)

In [61]:
a[a==b]
# all elements of a satisfy condition

array([0, 1, 2, 3, 4])

In [62]:
# summarizing operations now 

In [63]:
a.min()

np.int64(0)

In [64]:
a.sum()

np.int64(10)

In [65]:
a.mean()

np.float64(2.0)

In [66]:
a.max()

np.int64(4)

In [67]:
a.std()
# standard deviation

np.float64(1.4142135623730951)

In [68]:
n

array([[20, 30, 40],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [69]:
n.sum()
# ...etc 

np.int64(129)